AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-lambda-launcher

  Sample SAM Template for aws-lambda-launcher
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  LauncherFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: launcher/
      Handler: index.handler
      Runtime: nodejs14.x
      Events:
        Launcher:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /launch
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  LauncherApi:
    Description: "API Gateway endpoint URL for Prod stage for AWS Lambda Launcher function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/launch/"
  LauncherFunction:
    Description: "AWS Lambda Launcher Function ARN"
    Value: !GetAtt LauncherFunction.Arn
  LauncherFunctionIamRole:
    Description: "Implicit IAM Role created for AWS Lambda Launcher function"
    Value: !GetAtt LauncherFunctionRole.Arn
